In [ ]:
import numpy as np
from ipycanvas import Canvas, hold_canvas
from IPython.display import display

def draw_and_save(n_images):
    for i in range(n_images):
        canvas = Canvas(width=256, height=179)
        n_circles = np.random.randint(1, 6)
        n_plates = np.random.randint(1, 8)
        x_circle = np.random.randint(0, canvas.width, size=(n_circles))
        y_circle = np.random.randint(0, canvas.height, size=(n_circles))
        r = np.random.randint(10, 20, size=(n_circles))
        x_plates = np.random.randint(0, canvas.width, size=(n_plates))
        y_plates = np.random.randint(0, canvas.height, size=(n_plates))
        pos_plates = np.array([zip(x_plates, y_plates)])
        print(pos_plates)

        with hold_canvas(canvas):
            canvas.fill_style = 'black'
            canvas.fill_circles(x_circle, y_circle, r)
        return canvas

canvas = draw_and_save(1)

display(canvas)

5
3
[253 143 123  63 106]
[ 44 120  49  66 143]
[12 18 15 13 17]


Canvas(height=179, width=256)